### PR TITLE
Slater

### PR DESCRIPTION
**Pull request by sl8rw**
Added the submodule for pnwairfire/bluesky into our project, and updated readme.  Also added the raw bluesky 3.5.1 code.

### CODE REVIEW

**Comment by kylerlittle** [comment]
do we need to have the code here if we can just clone it ourselves

**Comment by sl8rw** [comment]
No we can clone it ourselves just fine, and I can totally remove the 3.5.1 code as we have access to all their versions.  But since we're doing our work in this repo easier to track commits imo

**Review by alm0st907 — COMMENTED** [review]
I think we should just document where the bluesky code is coming from and allow everyone to clone their own until we define our direction to go with this.

**Comment by sl8rw** [comment]
that's fine then, just didn't know if we wanna track updates or not

**Pull request closed without merging**
